game.o: game.c ../include/gf2d_graphics.h ../include/gf2d_types.h \
 ../include/gf2d_vector.h ../include/simple_logger.h
gf2d_graphics.o: gf2d_graphics.c ../include/gf2d_graphics.h \
 ../include/gf2d_types.h ../include/gf2d_vector.h \
 ../include/simple_logger.h
gf2d_vector.o: gf2d_vector.c ../include/gf2d_vector.h \
 ../include/gf2d_types.h
simple_logger.o: simple_logger.c ../include/simple_logger.h
